### PR TITLE
Feature/cache document classes

### PR DESCRIPTION
**Pull request by JohannesRudolph**
closes https://issues.hibernatingrhinos.com/issue/RDBC-340

### CODE REVIEW

**Comment by JohannesRudolph** [comment]
btw. a 4.2 release is due  ;-)

**Comment by ml054** [comment]
@JohannesRudolph The problem which I've seen with such approach is memory leak (this cache is static)
I will have a look at that and will try to find performant and memory leaks free solution.

**Comment by JohannesRudolph** [comment]
I think memory leaks shouldn’t be much of a problem, the typical use case
is a fairly static amount of document classes (10-100 maybe).

In highly recommend reviewing for concurrency issues though with all the
caches in that class.

As long as we get the convention method switched to return Class (my first
commit in the PR) we could have the caching in our own convention
configuration override. That would be fine as well.

Marcin Lewandowski <notifications@github.com> schrieb am Sa. 15. Juni 2019
um 18:38:

**Comment by ayende** [comment]
@ml054 While I know you can load & unload classes dynamically. How likely is that to be a problem for our scenario?

**Comment by ml054** [comment]
@ayende 
Let's move discussion to issue: https://issues.hibernatingrhinos.com/issue/RDBC-340#focus=streamItem-67-38195.0-0

I've described proposed solution which should mitigate possible memory leaks issues.

**Comment by JohannesRudolph** [comment]
I think we can close this as you mentioned it's fixed already 
> 974c21ce9fe8f92e6fcf5c9473d0f721f4f92b45 || Wed, 28 Aug 2019 13:22:01 +0200 || RDBC-340 JVM cache Class.forName in EntityToJson

**Pull request closed without merging**
